### PR TITLE
Refactor/proposal

### PR DESCRIPTION
**Pull request by xenide**
1. Backend API collectProposal function now uses a global provider, and was refactored
2. Creating proposal works
      - also programmatically disallowing users to add more than 10 actions for a proposal
3. Viewing proposals works 
      - Along with showing different kinds of actions according to your votes, if you have voted etc. 
4. Voting works (for, against)

### CODE REVIEW

**Review by hochbruj — APPROVED** [review]

**Comment by hochbruj** [comment]
Looks good to me. We probably should add some status update to the user when a tx is processing, confirmed, etc.

**Review by leodsoft — APPROVED** [review]
yeah looks good. I am by no means a react expert but the delta looks clean.

I assume queueWithLoading/executeWithLoading will be implemented in an upcoming cycle.

**Review by KennethAshley — APPROVED** [review]
🔥 Nice work on this one! Looks good!

**Comment by xenide** [comment]
@hochbruj, yes there are some frontend work we need to do to make it really responsive for the users. I made some cards regarding that. Feel free to add more
@leodsoft yes there are two cards sitting in the Voting column of our trello board for that

**Review by OliverNChalk — APPROVED** [review]
I very lightly skimmed the changes so approving but handing this over to the other reviewers to drive (who have all said yes :P)

**Pull request merged**
