### PR TITLE
allow cors

### PR DESCRIPTION
**Pull request by KennethAshley**
## Why
We need to enable cors!

## What changed?
Set settings in `next.config.js`

### CODE REVIEW

**Comment by xenide** [comment]
The preview still doesn't seem to work, especially when we go to the `Assets` tab. Perhaps the config file only modified the config for the serverless function and not the frontend itself?

**Comment by vbashkirtsev** [comment]
Just checked what https://governance-frontend-git-cors-vexchange.vercel.app/ returns. And I get inconsistent returns:
```
GET / HTTP/2
Host: governance-frontend-git-cors-vexchange.vercel.app
User-Agent: curl/7.66.0
Accept: */*

HTTP/2 200 
date: Wed, 09 Mar 2022 08:12:42 GMT
content-type: text/html; charset=utf-8
content-length: 25997
x-robots-tag: noindex
x-matched-path: /
cache-control: public, max-age=0, must-revalidate
etag: W/"daaf70ac3372c422aa1e6e6fef41ef9d3b2fb747bc0be4592164ad08449fe560"
access-control-allow-origin: *
content-disposition: inline; filename="index"
accept-ranges: bytes
age: 0
x-vercel-cache: MISS
server: Vercel
x-vercel-id: arn1:arn1::plklb-1646813561363-dcb3184b936c
strict-transport-security: max-age=63072000; includeSubDomains; preload
```
or
```
  HTTP/1.1 200 OK
  Date: Wed, 09 Mar 2022 08:22:57 GMT
  Content-Type: text/html; charset=utf-8
  Content-Length: 25997
  Connection: keep-alive
  X-Robots-Tag: noindex
  x-matched-path: /
  cache-control: public, max-age=0, must-revalidate
  etag: W/"daaf70ac3372c422aa1e6e6fef41ef9d3b2fb747bc0be4592164ad08449fe560"
  server: Vercel
  x-vercel-cache: HIT
  x-vercel-id: syd1::2n55n-1646811875145-44a2b5120838
```

No "access-control-allow-origin: *" header received causing "Access to XMLHttpRequest at 'https://jp.mainnet-node.vexchange.io/blocks/best' from origin 'https://governance-frontend-git-cors-vexchange.vercel.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." To be clear "the requested resource" is not https://jp.mainnet-node.vexchange/blocks/best but rather what is showing up in URL "https://governance-frontend-git-cors-vexchange.vercel.app". I have checked node load balancer log and there no contact from the browser when it gets no "access-control-allow-origin: *" header.

However when I get a response of a first kind Chrome contacts the node and proceeds without CORS errors. This commit appears to be correct way of getting CORS done (as per https://vercel.com/support/articles/how-to-enable-cors )

One thing is bothering me: response without "access-control-allow-origin: *" header has "x-vercel-cache: HIT" set suggesting that the response came back from the cache, not from the app itself. Feels like the case of cache poisoning. Inconsistent response is likely to the load balancer sending requests to different backend caches and some of them have cache entry without "access-control-allow-origin: *" header. If it is the case then caches should expire at some point and situation should right itself.

**Comment by vbashkirtsev** [comment]
Feels like CORS addition to vercel.json did the trick. At least vercel's edge in SYD now sends CORS header properly and it appears working on my end. I also checked it against ARN1 (Stockholm, Sweden) one which I tried above and others: IAD1 (Washington, USA), FRA1 (Frankfurt, Germany), HND1 (Tokyo, Japan). I guess we may safely assume that it will be flying anywhere else too.

PS: Someone in Vercel is really keen on aviation! When I saw their DCs names they just stick out to me due to my previous job as a pilot. Doubt they house their DCs next to runways :)
SYD - Sydney
ARN - Arlanda
IAD - Dulles International Airport
FRA - Frankfurt
HND - Haneda

**Comment by xenide** [comment]
So I updated the node address back to the JP one again. Seems to work now 👍 Also I changed Vercel's serverless function execution location to Tokyo to be close to our node as well. 

@KennethAshley can you ensure that we only change what we need in `next.config.js` and `vercel.json`? I have a feeling we might not need ALL the changes.

**Comment by vbashkirtsev** [comment]
Vercel's doc are a bit vague if these settings are needed in two places or just in one. May be it needs only changes in next.js and vercel.json modification simply forced the edge cache to refresh.

**Comment by KennethAshley** [comment]
@xenide @vbashkirtsev I think it was the one I added to the json file that did it. I dropped the commit that added the CORs information in the `next.config.js`

**Review by xenide — APPROVED** [review]
Looks good. I think you accidentally changed the node address to the Sydney one again. Can you change it back to the JP one?

**Pull request merged**
